import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
// import { Theme as ThemeRadix } from "@radix-ui/themes";
// import "@radix-ui/themes/styles.css";
// import "react-photo-view/dist/react-photo-view.css";

import "./../styles/index.scss";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "NextJS Blog",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "bg-background font-sans antialiased",
          inter.variable,
          inter.className,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <ThemeRadix> */}
          <div vaul-drawer-wrapper="" className="relative min-h-screen">
            {children}
          </div>
          {/* </ThemeRadix> */}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
