/* eslint-disable react/no-unknown-property */
// import { Theme as ThemeRadix } from "@radix-ui/themes";
// import "@radix-ui/themes/styles.css";
// import "react-photo-view/dist/react-photo-view.css";
import "./../styles/index.scss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import React from "react";

import { ThemeProvider } from "@/components/ThemeProvider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Fish's Blog",
  description: "Generated by create next app",
};
const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `(function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
              })(window, document, "clarity", "script", "o66yi70nm0");`,
          }}
        />
      </Head>
      <body
        className={cn(
          "bg-background font-sans antialiased",
          inter.variable,
          inter.className,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <ThemeRadix> */}
          <div vaul-drawer-wrapper="" className="relative min-h-screen">
            {children}
          </div>
          {/* </ThemeRadix> */}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
